version: '3'

services:
#  app:
#    container_name: app
#    restart: always
#    build: ..
#    ports:
#      - "8090:8090"
#    links:
#      - mongo
#  mongo:
##    container_name: mongo
#    image: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#    ports:
#      - "27017:27017"

  mongo:
    image: mongo
    #    networks:
    #      - crowdnet
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017

  gateway:
    image: nginx
    restart: always
    volumes:
      - ./gateway.nginx:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./privkey.pem:/etc/nginx/privkey.pem
    network_mode: "host"